/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF("/editedsuit.glb");
    return (
        <group ref={group} {...props} dispose={null}>
            {
                // pant
            }
            <mesh
                geometry={nodes.pant.geometry}
                material={materials["FABRIC 1_FRONT_4917.002"]}
                rotation={[-Math.PI, 0, -Math.PI]}
                material-color={props.pantColor}
            />
            <group rotation={[-Math.PI, 0, -Math.PI]}>
                {
                    // shirt
                }
                <mesh
                    geometry={nodes.hitman_shirt_for_upload.geometry}
                    material={materials["FABRIC 1_FRONT_4917.001"]}
                    material-color={props.shirtColor}
                />
                {
                    // collar
                }
                <mesh
                    geometry={nodes.hitman_shirt_for_upload_1.geometry}
                    material={materials["FABRIC 3_FRONT_4922"]}
                    material-color={props.collarColor}
                />
                {
                    // button
                }
                {props.showButton && (
                    <mesh
                        geometry={nodes.hitman_shirt_for_upload_2.geometry}
                        material={materials["Material3579.001"]}
                        material-color={props.buttonColor}
                    />
                )}
            </group>
            {
                // Court
            }
            <mesh
                geometry={nodes.suit.geometry}
                material={materials["Material.001"]}
                position={[-54.66, 38.95, 0]}
                rotation={[-Math.PI, 0, -Math.PI]}
                scale={1.02}
                material-color={props.courtColor}
            />
        </group>
    );
}

useGLTF.preload("/editedsuit.glb");
